# Generated by Django 4.2.3 on 2023-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_servicepost_teampost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampost',
            name='work',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Work:'),
        ),
    ]
