# Generated by Django 4.2.3 on 2023-07-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teampost_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamPost',
        ),
    ]
