# Generated by Django 4.2.3 on 2023-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0004_delete_teampost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Name:')),
                ('work', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Work:')),
                ('description', models.TextField(verbose_name='Haqqında:')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='upload/images', verbose_name='Şəkil Yerləşdir')),
                ('service_support', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Service Support:')),
                ('date', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Joining Date:')),
                ('years', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Years of experience:')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook URL')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter URL')),
                ('youtube', models.URLField(blank=True, max_length=255, null=True, verbose_name='YouTube URL')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
            },
        ),
    ]
