# Generated by Django 4.2.3 on 2023-07-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portifolio',
        ),
    ]
