# Generated by Django 4.2.3 on 2023-07-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portifolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
    ]
