# Generated by Django 4.2.3 on 2023-07-11 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portifolio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortifolioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=25, verbose_name='Tag: ')),
            ],
            options={
                'verbose_name': 'Portifolio Tag',
                'verbose_name_plural': 'Portifolio Tag',
            },
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portifolio_tag', to='portfolio.portifoliotag', verbose_name='Tag:'),
        ),
    ]
