# Generated by Django 4.2.3 on 2023-07-11 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portifoliotag_alter_portifolio_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portifolio',
        ),
        migrations.DeleteModel(
            name='PortifolioTag',
        ),
    ]
