# Generated by Django 4.2.3 on 2023-07-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0010_delete_portifolio_delete_portifoliotag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortifolioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=25, verbose_name='Tag: ')),
            ],
            options={
                'verbose_name': 'Portifolio Tag',
                'verbose_name_plural': 'Portifolio Tag',
            },
        ),
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='upload/images', verbose_name='Şəkil Yerləşdir')),
                ('image_22', models.ImageField(blank=True, null=True, upload_to='upload/images', verbose_name='Mobil Telefon üçün şəkil yerləşdir')),
                ('title', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Başlıq:')),
                ('portifolio_name', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Portfolio adı:')),
                ('description', models.TextField(verbose_name='Haqqında:')),
                ('client_name', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Client Name:')),
                ('date', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Date:')),
                ('website', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Website:')),
                ('title_1', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Başlıq:')),
                ('description_3', models.TextField(verbose_name='Haqqında:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portifolio_tag', to='portfolio.portifoliotag', verbose_name='Tag:')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
    ]
