# Generated by Django 4.2.3 on 2023-07-11 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portifolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Normal Portfolio'},
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portifolio_tag', to='portfolio.portifoliotag', verbose_name='Category:'),
        ),
    ]
