# Generated by Django 4.2.3 on 2023-07-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_portifolio_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portifoliotag',
            old_name='title',
            new_name='category',
        ),
    ]
