# Generated by Django 4.2.3 on 2023-07-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_rename_title_portifoliotag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='upload/images', verbose_name='Şəkil Yerləşdir')),
                ('portifolio_name', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Portfolio adı:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portifolio_tag2', to='portfolio.portifoliotag', verbose_name='Category:')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio 2',
            },
        ),
    ]
