# Generated by Django 4.2.3 on 2023-07-11 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_portifolio2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolio',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portifolio_tag', to='portfolio.portifoliotag', verbose_name='Category:'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='client_name',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Client Name:'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqında:'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='description_3',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqında:'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='portifolio_name',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Portfolio adı:'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='title',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='title_1',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AlterField(
            model_name='portifolio',
            name='website',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Website:'),
        ),
    ]
