# Generated by Django 4.2.3 on 2023-07-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_portifolio_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portifolio2',
        ),
    ]
