# Generated by Django 4.2.3 on 2023-07-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_delete_portifolio2'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolio',
            name='client_name_en',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Client Name:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='client_name_es',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Client Name:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='description_3_en',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='description_3_es',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='portifolio_name_en',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Portfolio adı:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='portifolio_name_es',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Portfolio adı:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='title_1_en',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='title_1_es',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='title_en',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='title_es',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='website_en',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Website:'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='website_es',
            field=models.CharField(blank=True, help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Website:'),
        ),
    ]
