# Generated by Django 4.2.3 on 2023-07-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('PhoneNo', models.CharField(max_length=255)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact form',
                'verbose_name_plural': 'Contact form',
            },
        ),
    ]
