# Generated by Django 4.2.3 on 2023-07-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePost',
        ),
    ]
