# Generated by Django 4.2.3 on 2023-07-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePost',
        ),
        migrations.DeleteModel(
            name='ServicePostElave',
        ),
    ]
