# Generated by Django 4.2.3 on 2023-07-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepost',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='title_3',
        ),
    ]
