# Generated by Django 4.2.3 on 2023-07-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_servicepost_description_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='description',
            field=models.TextField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Haqqında:'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='description2',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Haqqında:'),
        ),
    ]
