# Generated by Django 4.2.3 on 2023-07-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePost',
        ),
    ]
