# Generated by Django 4.2.3 on 2023-07-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='description2_en',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='description2_es',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='description_3_en',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='description_3_es',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='description_4_en',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='description_4_es',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='description_5_en',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='description_5_es',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Haqqında:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='title_1_en',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='title_1_es',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='title_2_en',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='title_2_es',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='title_3_en',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='title_3_es',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='title_en',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
        migrations.AddField(
            model_name='servicepost',
            name='title_es',
            field=models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, null=True, verbose_name='Başlıq:'),
        ),
    ]
