# Generated by Django 4.2.3 on 2023-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeslimationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Name:')),
                ('work', models.CharField(help_text='Ümumi dəyər 255 olmalıdır!', max_length=255, verbose_name='Work:')),
                ('description', models.TextField(verbose_name='Haqqında:')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='upload/images', verbose_name='Şəkil Yerləşdir')),
            ],
            options={
                'verbose_name': 'Teslimation',
                'verbose_name_plural': 'Teslimation',
            },
        ),
    ]
