# Generated by Django 4.2.3 on 2023-07-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslimationpost',
            name='description',
            field=models.TextField(verbose_name='The answer:'),
        ),
    ]
