# Generated by Django 4.2.3 on 2023-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_teslimationpost_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('PhoneNo', models.CharField(max_length=255)),
                ('Message', models.TextField()),
            ],
        ),
    ]
