# Generated by Django 4.2.3 on 2023-07-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_contactformentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformentry',
            options={'verbose_name': 'Contact form', 'verbose_name_plural': 'Contact form'},
        ),
    ]
