# Generated by Django 4.2.3 on 2023-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_contactformentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAdressFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailAddress', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Email Address',
                'verbose_name_plural': 'Email Address',
            },
        ),
    ]
